### ISSUE TITLE
Find config files in custom modules more advanced

### ISSUE THREAD

**Issue by jlahijani** [trk/Mystique#12]
Currently, Mystique-next cannot find my Mystique config files in my custom module located here:
/site/modules/MyModule/foo/bar/configs/Mystique.mytestfield.php

Possible to fix?

**Comment by trk** [comment]
This is not an issue, module not checking these folders. I don't want to scan all templates subfolders or module sub folders.

Maybe, i can add a custom path option for field type config.

Structure of module config files :

site/modules/*/configs/`{Mystique.*.php, mystique.*.php, mystique.*.json, Mystique.*.json}`
site/templates/configs/`{Mystique.*.php, mystique.*.php, mystique.*.json, Mystique.*.json}`
