### ISSUE TITLE
Merge next branch

### ISSUE THREAD

**Issue by ivangretsky** [trk/Mystique#15]
Good day, @trk !

Every time I come back to your superb module, I am on a crossroads - which version should I use: master or next. They've been split for quite some time now. So my questions are:

1. Which version do you use in production?
2. Which version do you recommend to start a project with?
3. Isn't it time to merge next branch into master yet and kill the dilemma? Hope it will happen soon 🙏

Thanks!

**Comment by trk** [comment]
My left hand broken, a car crashed to me and i am limited about using computer. I will merge it after make latest checks.

**Comment by ivangretsky** [comment]
Oh, sorry! I wish you a quick recovery,

**Comment by trk** [comment]
Merged
