### ISSUE TITLE
Can't edit Repeater Matrix in admin which contains a Mystique field

### ISSUE THREAD

**Issue by ivangretsky** [trk/Mystique#17]
Good day @trk !

I am using Mystique fields inside my Repeater and Repeater Matrix items. Those items are indeed pages under `Admin/Repeaters` in the pages tree. If I go there in admin interface and try to edit these pages, I get an error (see the screenshot below):

![изображение](https://user-images.githubusercontent.com/6697626/148644431-5f4ac114-9231-431f-b206-f797d6d63f7b.png)

If I remove the Mystique field from the RM template, everything works like it should. Could you please look into this?

**Comment by trk** [comment]
Can you try next branch ?

**Comment by ivangretsky** [comment]
I am using 0.0.17. I think it is next branch.

**Comment by trk** [comment]
Update your local next branch with latest repo files, you have old files. this line commented on latest files

https://github.com/trk/Mystique/blob/next/FieldtypeMystique.module.php#L118

**Comment by ivangretsky** [comment]
I did upgrade and that issue is gone. But here goes another one in another place:
![изображение](https://user-images.githubusercontent.com/6697626/148653291-4714a3a1-068d-4259-ab8a-4a6e52c39967.png)

**Comment by trk** [comment]
When you get this error ?

**Comment by ivangretsky** [comment]
Same case - when tying to edit a RM page in admin.

**Comment by trk** [comment]
I added a quick fix here https://github.com/trk/Mystique/blob/next/InputfieldMystique.module.php#L172 can you update and re-check it ?
