### ISSUE TITLE
Inputfield's assets are not being preloaded

### ISSUE THREAD

**Issue by Lazerproof** [trk/Mystique#18]
Hi @trk . Thank you for your effort. 

JS, CSS assets of the fields that are present inside Mystique that is inside ajax-loaded Repeater/Matrix field are not being preloaded.

InputfieldRepeater has a method that preloads assets, but probably because subfields of Mystique field are managed with custom FormManger and are not 'native' fields this method can't handle their assets. 

https://github.com/processwire/processwire/blob/master/wire/modules/Fieldtype/FieldtypeRepeater/InputfieldRepeater.module#L240

Example of the InputfieldToggle without loaded assets:
![](https://360px.com.ua/monosnap/chrome_8fpa7eFx0f.jpg)

As a solution, we can have some method inside FormManager that will return an array of all inputfield types and then we can loop through them calling modules()->loadModuleFileAssets('InputfieldName');

**Comment by ivangretsky** [comment]
Yep, have the same issue with a custom inputfield.

**Comment by Lazerproof** [comment]
Hi @trk 
The current workaround that I'm using:
In autoload module
```
public function init() {
		$this->wire()->addHookBefore('InputfieldRepeater::render', function ($evet) {
			$object = $evet->object;
			$field = $object->hasField;
			$page = $object->hasPage;

			if ($field->name === 'content_blocks') {

				$templateId = $field->get('template_id');
				$template = $templateId ? $this->wire()->templates->get($templateId) : null;
				$fieldgroup = $template ? $template->fieldgroup : null;

				if ($fieldgroup->hasField('content_block_settings')) {
					$field = $fieldgroup->get('content_block_settings');
					$fieldtype = $field->type;
					$resource = $fieldtype->loadResource($field->resource, $page, $field);

					$fieldtypes = [];

					$this->getFieldTypes($resource['fields'], $fieldtypes);


					foreach ($fieldtypes as $fieldtype) {
						$this->wire()->modules->loadModuleFileAssets($fieldtype);
					}
				}
			}
		});
	}

	protected function getFieldTypes(array $fields, &$fieldtypes) {
		foreach ($fields as $field) {
			if (isset($field['type'])) $fieldtypes[] = $field['type'];

			if (isset($field['children']) && is_array($field['children'])) {
				$this->getFieldTypes($field['children'], $fieldtypes);
			}
		}
	}
```

**Comment by trk** [comment]
I pushed an update, can you update module and re-test it ?

**Comment by digitalbricks** [comment]
I just testet version 0.0.20 with Repeater and RepeaterMatrix fields and had no issue at all. Seems to be fixed.
(As first-time user of Mystique i ended up here, more or less, by accident but wanted to leave some feedback on that issue)

**Comment by trk** [comment]
Thanks @digitalbricks
