### ISSUE TITLE
Execution Time

### ISSUE THREAD

**Issue by sebastiandittrich** [trk/Mystique#6]
The process of finding all Mystique config files takes very long. 

This part of the code alone takes about 200-300ms (which doubles loading times) in my setup with 6 Modules (Mystique excluded): 
https://github.com/trk/Mystique/blob/c15a95a2d9de4bdd4186ea293f76aec01cf9e672/Mystique.module.php#L118-L124

I have encountered this issue while developing a module with a node_modules folder in it. With this node_modules inside my module, a page load took about 15 seconds, which is definitely too much. But there is no option to disable searching inside of this large folder.

Maybe it would be a good idea to give developers the possibility to further restrict the directories in which should be searched with the `excludeDirNames` option for `Wire->files->find` ([Documentation](https://processwire.com/api/ref/wire-file-tools/find/)). 
Another option would be to register all config files by hand, or registering just individual directories. Something like this: 
```php
// Inside another module
$wire->modules->get('Mystique')->registerConfigPath('path/to/config/files/');
```

**Comment by trk** [comment]
I know,

I used `glob` function for find config files, but on some of servers glob function not working well.

You can see details at here : https://processwire.com/talk/topic/21285-mystique-fieldtype-inputfield-build-dynamic-fields-and-store-data-by-using-config-file/?tab=comments#comment-196700

Normally i want to use `glob` function :

Can you return this on `finder` function and make test ?

```php
return glob('{' . $this->config->paths->templates . 'configs/Mystique.*.php,' . $this->config->paths->siteModules . '*/configs/Mystique.*.php}', GLOB_BRACE | GLOB_NOSORT);

```

**Comment by trk** [comment]
@sebastiandittrich 

I updated module, added an option for use `glob` method for find config files, can you update module and test it ?

<img width="1458" alt="Ekran Resmi 2020-07-23 17 47 10" src="https://user-images.githubusercontent.com/455983/88300808-91f0cb00-cd0c-11ea-82bc-3a8d13ec09b8.png">

**Comment by sebastiandittrich** [comment]
Thanks for the quick reply!

I've downloaded and tested v0.0.15, but with the `glob` option enabled it isn't finding my config file at `site\modules\BookingStudio\configs\Mystique.addon-config.php`. The dropdown in the edit field page is completely empty, even the example configs are not visible.

After doing some tests, it seems like glob is not working for me with the `GLOB_BRACE` option enabled. Without this option (and only the siteModules directory specified), it works. 

But what do you think about only searching in the `templates` directory for Mystique config files for user-generated configs? Modules could either register their config file paths explicitly, or, what I personally think would be more intuitive, add their configs directly without the need of a config file. Something like this: 

```php
$this->addHookAfter('Mystique::getConfigs', function(HookEvent $event) {
    $configs = $event->return;
    $configs[] = [
        'title' => 'Module config file'
        // ...
    ]
    $event->return = $configs;
});
```

**Comment by trk** [comment]
I want to keep module works with config files.

On my side `glob` method working, on local and online servers. I know this issue, for the moment i don't have a solution. Maybe we need a better `core` finder module or class on processwire side.

**Comment by sebastiandittrich** [comment]
Ok, seems to be [this bug](https://bugs.php.net/bug.php?id=42501).

**Comment by sebastiandittrich** [comment]
But with the nts version of php it works, and is very fast! Thank you! Tested it with my `node_modules` folder, and it took only 0.9ms to search, instead of 15s.
