### ISSUE TITLE
Why is ready used instead of init?

### ISSUE THREAD

**Issue by sebastiandittrich** [trk/Mystique#7]
This Module is initializing in the `ready` Method of Processwire, which is called when the current page is ready to render. 

See here:
https://github.com/trk/Mystique/blob/c6774033f32ae27901f0a814fe1ed2548fa781c9/Mystique.module.php#L93

This leads to the issue, that other modules that are trying to access Mystique Fields in their `init` method are getting `null` for every requested field instead of the actual value. I've tried to replace `ready` with `init`, and everything works as expected. So, is there a reason that you are using`ready`, or could you maybe change this, so that other modules can access Mystique Fields in their `init` method?

PS: Great module, saves a lot of work setting up unneccesary fields!

**Comment by trk** [comment]
Can you make a pull request ?
